server:
  port: 1111
spring:
  datasource:
    username: fakhri
    password: 1234567890
    url: jdbc:postgresql://localhost:5432/dans_db?user=fakhri&password=1234567890
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
jwt:
  secret: eyJhbGciOiJIUzUxMiJ9eyJzdWIiOiJhYmR1cnJvaG1hbiIsImlhdCI6MTY2NTY1MDM5MSwiZXhwIjoxNjY1Njg2MzkxfQ8kAdf1zjXZNcWSfV3XoXF71QOJwt3uYAu1HkE3oSKzZwMpO3OxesoaaqRT1nKuFAkInLa7xlDY1TvFy1zP8g
